version: '3.8'

services:
  jekyll:
    image: jekyll/jekyll:latest
    command: jekyll serve --watch --force_polling --host 0.0.0.0
    ports:
      - "4000:4000"
    environment:
      - JEKYLL_ENV=development
    # Optional: Add this if you want to keep Gem dependencies installed across container restarts
    # to avoid reinstalling them every time.
    # "vendor/bundle" は Gemfile.lock の保存先です
    volumes:
      - .:/srv/jekyll
      - bundle_cache:/usr/local/bundle
    working_dir: /srv/jekyll

volumes:
  bundle_cache:
